<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.48.0" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.118" />
    <PackageReference Include="System.Data.SQLite.EF6" Version="1.0.118" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.118" />
    <!-- Morse Code Decoder Dependencies -->
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="Microsoft.ML" Version="3.0.1" />
    <PackageReference Include="Accord.MachineLearning" Version="3.8.0" />
    <PackageReference Include="OxyPlot.Wpf" Version="2.1.2" />
  </ItemGroup>

</Project>
